<a href="https://colab.research.google.com/github/JiHoonMin/python/blob/main/fibonacci.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## Question 1

def fibonacci(n):
  if n <= 1:
    return n
  else:
    return (fibonacci(n-1)+fibonacci(n-2))
for i in range(0,10):
  print(fibonacci(i))


0
1
1
2
3
5
8
13
21
34


In [ ]:
## Question 2
sum_odd = 0
for i in range(0,10):
  if fibonacci(i)%2==1:
    sum_odd = sum_odd + fibonacci(i)

print(sum_odd)

44


In [ ]:
## Question 3
import numpy as np
a = np.arange(1,31)
b = a.reshape((6,5))
print(b)

print("\n\t---------------after numpy.split()---------------\n")
np.vsplit(b,3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]

	---------------after numpy.split()---------------



[array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]), array([[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]])]

In [ ]:
## Question 4
import numpy as np

emp_array = []
for i in range(0,11):
  if i % 2 == 0:
    emp_array.append(0)
  else :
    emp_array.append(i)
print(emp_array)


[0, 1, 0, 3, 0, 5, 0, 7, 0, 9, 0]
