<a href="https://colab.research.google.com/github/JiHoonMin/python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
import numpy as np
a = np.array[1,2,3,4])
print(type(a))
print(a)

SyntaxError: ignored

In [ ]:
l = [[1,2,3],[4,5,6],[7,8,9]]
a = np.array(l)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.shape)
print(a.dtype)

(3, 3)
int64


In [ ]:
a = np.arange(10,20)
b = a.reshape((2,5))
print(b)

[[10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0,0])

1


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0])

[1 2 3]


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[:,0])

[1 4 7]


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a[1,1] = 0
print(a)

[[1 2 3]
 [4 0 6]
 [7 8 9]]


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a[0] = [0,0,0]
print(a)

[[0 0 0]
 [4 5 6]
 [7 8 9]]


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

a[:,0] = [0,0,0]
print(a)

[[0 2 3]
 [0 5 6]
 [0 8 9]]


In [ ]:
x = np.arange(0,10,2)
print(x)

[0 2 4 6 8]


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.min())
print(a.max())
print(a.mean())

1
9
5.0


In [ ]:
a = np.zeros((3,3))
print(a)
b = np.ones((2,2))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]


In [ ]:
a = np.random.rand(5,5)
print(a)

[[0.26145092 0.5889363  0.33822675 0.52359265 0.02740778]
 [0.96288968 0.74922545 0.13970688 0.59039982 0.80690374]
 [0.9067168  0.00327751 0.61932113 0.13889945 0.63811285]
 [0.75718716 0.04495809 0.10931042 0.83615957 0.29435595]
 [0.79666349 0.49924387 0.67423402 0.56651302 0.52164296]]


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
np.arange(3) + 5

array([5, 6, 7])

In [ ]:
np.ones((3,3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [ ]:
np.arange(3).reshape((3,1))+np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])